[workspace]
resolver = "2"

members = [    
    "timelock",
    #"deployer/deployer",
    #"deployer/contract",
]

[profile.release-with-logs]
inherits = "release"
debug-assertions = true

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[workspace.dependencies.soroban-sdk]
version = "0.2.1"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "8e3d9642"


[patch."https://github.com/stellar/rs-soroban-sdk"]
soroban-sdk = { path = "../rs-soroban-sdk/soroban-sdk" }
soroban-spec = { path = "../rs-soroban-sdk/soroban-spec" }

[patch."https://github.com/stellar/rs-stellar-xdr"]
stellar-xdr = { path = "../rs-stellar-xdr/" }

[patch."https://github.com/stellar/rs-soroban-env"]
soroban-env-common = { path = "../rs-soroban-env/soroban-env-common" }
soroban-env-guest = { path = "../rs-soroban-env/soroban-env-guest" }
soroban-env-host = { path = "../rs-soroban-env/soroban-env-host/" }